### ISSUE TITLE
Dependency conflict 

### ISSUE THREAD

**Issue by BachoSeven** [XayOn/katcr#129]
Hi, I'm unsure how I could resolve this, I tried using normal pip and also pipx(contained installation) but I always get this:
```
ERROR: pygogo 0.10.0 has requirement future~=0.15.2, but you'll have future 0.18.2 which is incompatible.
```

**Comment by XayOn** [comment]
Hi @BachoSeven , did you try a virtualenv? 
Conflicts between dependencies on installed packages are pretty common.

However, I've updated the project, using poetry now and updated all deps, so this shoulD work now for you.

**Comment by BachoSeven** [comment]
I was able to install through `pip`, but it looks like it's 2.0.1, while your last release here is 3.0.0a. I also think it's not updated because typing `katcr --help` does not show the `--engines` option, for instance.

**Comment by XayOn** [comment]
Hi @BachoSeven I've just uploaded "katcr-3.0.0a0" to pypi, have in account that its an alpha.

This is basically an "emergency" alpha, as most torrent providers had died or changed radically their webpages. (I.E, tpb using javascript...) making previous version hardly usable except with jackett.

It comes with major changes (and some drawbacks 😢  )

Basically, as improvements:
- Its more magnet-centered, looks for magnet links with a regex thus making scrapping a lot easier and a smaller codebase (more mantainable).
- Huge cleanup of dead torrent sites, added a few new ones 
- Added torrent streaming capabilities (just set your favourite player on the PLAYER environment variable, and use --stream and --interactive togheter)
- Jackett support works nice
- Docker now directly sets katcr as entrypoint

As drawbacks:
- Documentation is still WIP
- KatBot is gone, the telegram part has to be rewritten
- Tests are gone too
- It now requires libtorrent (will make this part optional with an extra section tomorrow)

**Comment by BachoSeven** [comment]
That sounds great, especially about the Jackett support, I actually discovered `katcr` while looking for a nice cli tool for Jackett, I agree that using Jackett is gonna be more reliable than manually updating the torrent sites

P.S. I'll try to make an AUR package for this tool sometime soon

**Comment by XayOn** [comment]
The AUR package would be really nice!

I just improved the jackett support a bit, it wasnt working with torrentstream, and I've added a configuration file to store the api key  and URL.

**Comment by BachoSeven** [comment]
Hei, I've been trying to make the AUR package, but I have some technical difficulties, since on Arch I need to follow the [Packaging Guidelines](https://wiki.archlinux.org/index.php/Python_package_guidelines), which means I cannot use `pip` to install, but rather I have to add all necessary dependencies. Moreover, since not all dependencies listed in `pyproject.toml` were present in Arch/AUR, I went ahead and packaged some of them, and some of the dependencies of the dependencies(...)

Unfortunately, even after doing all that, the tests fail because, being on Arch, `robobrowser` pulls in the _latest_ version of `werkzeug`, rather than `0.16.1` as required by your `torrentmirror` package. So, the unsolved library breakings (see [1](https://github.com/jmcarp/robobrowser/issues/96), [2](https://github.com/jmcarp/robobrowser/issues/93)) introduced in robobrowser by newer versions of werkzeug make the tests fail. `robobrowser` seems to be unmaintained, so do you think I should make a package for `werkzeug`==0.16?

**Comment by BachoSeven** [comment]
If you would not mind(it would make things a lot easier), you could try using the workaround shown [here](https://github.com/jmcarp/robobrowser/issues/93#issuecomment-650640171):
Namely, adding
``` py
import werkzeug
werkzeug.cached_property = werkzeug.utils.cached_property
```
BEFORE `import robobrowser`, so in our case it would be necessary [here](https://github.com/XayOn/torrentmirror/blob/9e09f994f34c51ad37e4662970a02c173b3c45a4/torrentmirror/__init__.py#L8) for `torrentmirror` (and perhaps [here](https://github.com/XayOn/katcr/blob/48a5ac676792b836fbd11c62a8579092fce3f733/tests/unit/conftest.py#L7) for the test in this repo). This way, I could package using the latest `werkzeug` version.

What do you think?

**Comment by BachoSeven** [comment]
btw, here are my packages for [torrentmirror](https://aur.archlinux.org/packages/python-torrentmirror-git/) and [katcr](https://github.com/BachoSeven/aur/blob/master/katcr/PKGBUILD) (latter is not uploaded because it doesn't build)

**Comment by XayOn** [comment]
@BachoSeven I actually closed this because robobrowser is no longer a dependency 😟 

Maybe you're packaging an older version?

**Comment by XayOn** [comment]
Oh! i see, it's a subdependency of torrentmirror, let's continue this discussion over there. I've opened https://github.com/XayOn/torrentmirror/issues/1

**Comment by BachoSeven** [comment]
Feel free to add the AUR [package](https://aur.archlinux.org/packages/katcr/) to the installation methods, it works now(with optional support for streaming as well).

**Comment by XayOn** [comment]
Done, thanks @BachoSeven 👍🏽
