### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by BachoSeven** [XayOn/katcr#141]
**Describe the bug**

Cannot search via the default engines:
```
> katcr search ubuntu

Starting search on Katcr, ThePirateBay, Eztv, NyaaSi, Skytorrents

  AttributeError

  'NoneType' object has no attribute 'text'

  at .local/lib/python3.8/site-packages/torrentmirror/__init__.py:46 in get_proxies
      42│             status = row.find(class_='proxy-statues')
      43│             percentage = row.find(class_='proxy-like').find(class_='counts')
      44│             proxies[link.find('span').text].append(
      45│                 dict(link=name_.find('a').attrs['href'],
    → 46│                      percentage=int(percentage.text.replace('%', '')),
      47│                      status=status.text.strip()))
      48│
      49│     proxies = dict(proxies)
      50│     pickle.dump(proxies, CACHE_FILE.open('wb'))
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f0be12ae2b0>
```

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Version**
- katcr 3.0.1 (latest PyPi, installed through `pip` so I think it's pretty much git master)

**Comment by XayOn** [comment]
For some reason, torrentmirror seems to have stopped working.
I've updated a change that allows katcr to work if torrentmirror fails, that is specially useful if you use Jackett engine.

**Comment by XayOn** [comment]
Most important providers seem to be working fine without proxies right now.

**Comment by XayOn** [comment]
@BachoSeven I've uploaded a new release with this change and another minor one. 
Relying on scrapping always causes troubles, this release allows katcr to work without available proxies, thus allowing a complete jackett instalation without any scrapping.
